CREATE TABLE IF NOT EXISTS public.pickup_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  college_id BIGINT REFERENCES public.colleges(id),
  name TEXT NOT NULL UNIQUE,
  address TEXT,
  city TEXT,
  state TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.pickup_locations
ADD COLUMN IF NOT EXISTS college_id BIGINT REFERENCES public.colleges(id);

CREATE INDEX IF NOT EXISTS pickup_locations_college_active_sort_idx
ON public.pickup_locations(college_id, active, sort_order);

ALTER TABLE public.pickup_locations ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'pickup_locations'
      AND policyname = 'Anyone can read active pickup locations'
  ) THEN
    CREATE POLICY "Anyone can read active pickup locations"
    ON public.pickup_locations
    FOR SELECT
    TO anon, authenticated
    USING (active = TRUE);
  END IF;
END $$;

INSERT INTO public.pickup_locations (college_id, name, address, city, state, sort_order)
SELECT id, name || ' parent drop-off desk', 'Local collection desk', city, state, 1
FROM public.colleges
WHERE name IN (
  'Stanford University',
  'University of California, Berkeley',
  'University of Southern California',
  'UCLA',
  'Arizona State University',
  'University of Texas at Austin',
  'New York University',
  'Boston University'
)
ON CONFLICT (name) DO UPDATE SET
  college_id = EXCLUDED.college_id,
  address = EXCLUDED.address,
  city = EXCLUDED.city,
  state = EXCLUDED.state,
  sort_order = EXCLUDED.sort_order,
  active = TRUE;
