CREATE TABLE IF NOT EXISTS public.colleges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  city TEXT,
  state TEXT,
  logo_url TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.pickup_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  college_id BIGINT NOT NULL REFERENCES public.colleges(id),
  name TEXT NOT NULL UNIQUE,
  address TEXT,
  city TEXT,
  state TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.parent_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  parent_name TEXT NOT NULL,
  parent_email TEXT NOT NULL UNIQUE,
  parent_phone TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.pre_registrations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  parent_name TEXT NOT NULL,
  parent_email TEXT NOT NULL UNIQUE,
  parent_phone TEXT NOT NULL,
  college_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number TEXT NOT NULL UNIQUE,
  parent_profile_id UUID REFERENCES public.parent_profiles(id),
  status TEXT NOT NULL DEFAULT 'confirmed',
  parent_name TEXT NOT NULL,
  parent_email TEXT NOT NULL,
  parent_phone TEXT NOT NULL,
  college_name TEXT NOT NULL,
  category TEXT NOT NULL,
  pickup_location TEXT,
  item_details TEXT,
  student_name TEXT NOT NULL,
  student_phone TEXT NOT NULL,
  dorm TEXT NOT NULL,
  room TEXT,
  instructions TEXT,
  payment_method TEXT NOT NULL,
  total_cents INTEGER NOT NULL DEFAULT 1800,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS orders_parent_email_idx ON public.orders(parent_email);
CREATE INDEX IF NOT EXISTS orders_parent_profile_id_idx ON public.orders(parent_profile_id);
CREATE INDEX IF NOT EXISTS orders_status_idx ON public.orders(status);
CREATE INDEX IF NOT EXISTS orders_created_at_idx ON public.orders(created_at);
CREATE INDEX IF NOT EXISTS parent_profiles_parent_email_idx ON public.parent_profiles(parent_email);
CREATE INDEX IF NOT EXISTS parent_profiles_user_id_idx ON public.parent_profiles(user_id);
CREATE INDEX IF NOT EXISTS pre_registrations_parent_email_idx ON public.pre_registrations(parent_email);
CREATE INDEX IF NOT EXISTS pre_registrations_college_name_idx ON public.pre_registrations(college_name);
CREATE INDEX IF NOT EXISTS pickup_locations_college_active_sort_idx ON public.pickup_locations(college_id, active, sort_order);

ALTER TABLE public.colleges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pickup_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parent_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pre_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT INSERT ON public.pre_registrations TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.parent_profiles TO authenticated;
GRANT SELECT, INSERT ON public.orders TO authenticated;

CREATE POLICY "Anyone can read active colleges"
ON public.colleges
FOR SELECT
TO anon, authenticated
USING (active = TRUE);

CREATE POLICY "Anyone can read active pickup locations"
ON public.pickup_locations
FOR SELECT
TO anon, authenticated
USING (active = TRUE);

CREATE POLICY "Parents can create their own orders"
ON public.orders
FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.parent_profiles
    WHERE parent_profiles.id = orders.parent_profile_id
      AND parent_profiles.user_id = auth.uid()
  )
);

CREATE POLICY "Parents can create their own profile"
ON public.parent_profiles
FOR INSERT
TO authenticated
WITH CHECK (user_id = auth.uid());

CREATE POLICY "Anyone can create pre registrations"
ON public.pre_registrations
FOR INSERT
TO anon, authenticated
WITH CHECK (
  length(parent_name) BETWEEN 1 AND 120
  AND parent_email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'
  AND parent_phone ~ '^[0-9]{10}$'
  AND length(college_name) BETWEEN 1 AND 120
);

CREATE POLICY "Parents can read their own profile"
ON public.parent_profiles
FOR SELECT
TO authenticated
USING (user_id = auth.uid());

CREATE POLICY "Parents can update their own profile"
ON public.parent_profiles
FOR UPDATE
TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

CREATE POLICY "Parents can read their own orders"
ON public.orders
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.parent_profiles
    WHERE parent_profiles.id = orders.parent_profile_id
      AND parent_profiles.user_id = auth.uid()
  )
);

INSERT INTO public.colleges (name, city, state)
VALUES
  ('Stanford University', 'Stanford', 'CA'),
  ('University of California, Berkeley', 'Berkeley', 'CA'),
  ('University of Southern California', 'Los Angeles', 'CA'),
  ('UCLA', 'Los Angeles', 'CA'),
  ('Arizona State University', 'Tempe', 'AZ'),
  ('University of Texas at Austin', 'Austin', 'TX'),
  ('New York University', 'New York', 'NY'),
  ('Boston University', 'Boston', 'MA')
ON CONFLICT (name) DO UPDATE SET
  city = EXCLUDED.city,
  state = EXCLUDED.state;

INSERT INTO public.pickup_locations (college_id, name, address, city, state, sort_order)
SELECT id, name || ' parent drop-off desk', 'Local collection desk', city, state, 1
FROM public.colleges
WHERE name IN (
  'Stanford University',
  'University of California, Berkeley',
  'University of Southern California',
  'UCLA',
  'Arizona State University',
  'University of Texas at Austin',
  'New York University',
  'Boston University'
)
ON CONFLICT (name) DO UPDATE SET
  college_id = EXCLUDED.college_id,
  address = EXCLUDED.address,
  city = EXCLUDED.city,
  state = EXCLUDED.state,
  sort_order = EXCLUDED.sort_order,
  active = TRUE;
