CREATE TABLE IF NOT EXISTS public.colleges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  city TEXT,
  state TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'confirmed',
  parent_name TEXT NOT NULL,
  parent_email TEXT NOT NULL,
  parent_phone TEXT NOT NULL,
  college_name TEXT NOT NULL,
  category TEXT NOT NULL,
  item_details TEXT,
  student_name TEXT NOT NULL,
  student_phone TEXT NOT NULL,
  dorm TEXT NOT NULL,
  room TEXT,
  instructions TEXT,
  payment_method TEXT NOT NULL,
  total_cents INTEGER NOT NULL DEFAULT 1800,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS orders_parent_email_idx ON public.orders(parent_email);
CREATE INDEX IF NOT EXISTS orders_status_idx ON public.orders(status);
CREATE INDEX IF NOT EXISTS orders_created_at_idx ON public.orders(created_at);

ALTER TABLE public.colleges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read active colleges"
ON public.colleges
FOR SELECT
TO anon, authenticated
USING (active = TRUE);

CREATE POLICY "Anyone can create prototype orders"
ON public.orders
FOR INSERT
TO anon, authenticated
WITH CHECK (TRUE);

INSERT INTO public.colleges (name, city, state)
VALUES
  ('Stanford University', 'Stanford', 'CA'),
  ('University of California, Berkeley', 'Berkeley', 'CA'),
  ('University of Southern California', 'Los Angeles', 'CA'),
  ('UCLA', 'Los Angeles', 'CA'),
  ('Arizona State University', 'Tempe', 'AZ'),
  ('University of Texas at Austin', 'Austin', 'TX'),
  ('New York University', 'New York', 'NY'),
  ('Boston University', 'Boston', 'MA')
ON CONFLICT (name) DO NOTHING;
